/* CREATE A FAULTY CALCULLATOR USING JAVASCRIPT

THIS FAULTY CALCULATOR DOES FOLLOWING:
1.  IT TAKES TWO NUMBERS AS INPUT FROM THE USER 
2.  IT WILL PERFORM WRONG OPERATIONS AS FOLLOWS:

+ ---> -
* ---> +
- ---> /
/ ---> **

IT PERFORMS WORONG OPERATION 10% OF THE TIMES */